### ISSUE TITLE
Is this repository maintained?

### ISSUE THREAD

**Issue by plandolt** [php-translation/phraseapp-adapter#18]
This repository requires ^0.2.0 of php-translation/common. But there is already 3.* available. Thus the question: is this repository still maintained or considered archived?

**Comment by welcoMattic** [comment]
Hi @scuben, I think that you should consider this adapter as unmaintained, unless if you want to improve it, feel free to open a PR.
But, I currently working on this [PR](https://github.com/symfony/symfony/pull/38475) on Symfony, that will introduce Translation Providers directly into Symfony, and I plan to implement a Provider for Phrase later on.

Thanks for your comment

**Comment by plandolt** [comment]
Hi @welcoMattic, oh wow I was not aware of the current work adding this functionality to the symfony core. Thank you for pointing me to it.
