### ISSUE TITLE
Problem with symfony-profiler

### ISSUE THREAD

**Issue by prolic** [php-translation/phraseapp-adapter#2]
After integrating this in a real symfony application, I receive the following error on the website:

```
An error occurred while loading the web debug toolbar (404: Not Found).
Do you want to open the profiler?
```

when I click yes, this comes up:

```
Token not found
Token "59942c" was not found in the database.
```

Other than that, the translation import / export and displaying seems to work.

Any ideas what's going on? @Nyholm

**Comment by Nyholm** [comment]
I've seen this error before. It is really hard to find. I *believe* there is a service or a typo in the code that only run in admin... Sorry for not being more clear.
